### ISSUE TITLE
error while making a kit

### ISSUE THREAD

**Issue by TetroYT** [AndreasHGK/EasyKits#11] opened 2019-09-18 06:08 UTC
![0B611D1D-0669-4E53-BB47-24AD82CB9E71](https://user-images.githubusercontent.com/49662383/65118424-f8b5a180-d9e2-11e9-861b-653feac261cd.png)

i got this while making my first none locked kit i dont know if that has anything to do with the error

**Comment by TetroYT** [comment] 2019-09-18 15:54
i did some testing and it seems to be that if i have more than 3 categories then it crashes when i try to make a kit

**Comment by AndreasHGK** [comment] 2019-09-19 05:02
Ill look into it when i can

**Comment by AndreasHGK** [comment] 2019-09-19 05:03
Can you show the kits.yml file and categories.yml ?

**Comment by TetroYT** [comment] 2019-09-19 06:33
categories:

---
§aStandard Kits:
  kits:
  - §cStarter
  - §bPVP
  - §cDo§6madia
  - §dNeos
  - §eMiza
  locked: false
§6GKits:
  kits: []
  locked: true
§bSKits:
  kits:
  - §l§e-=+ §bCronic §l§e+=-§r
  - §l§e<§c§k:§r§l§e> §cDemeter §l§e<§c§k:§r§l§e>
  - §l§e<§c§k!!§r§l§e>§aChyros§e<§c§k!!§r§l§e>
  - §l§c=-= §dXypnos §c=-=
  - §3Vote Package
  locked: true
...

**Comment by TetroYT** [comment] 2019-09-19 06:34
kits:

---
§l§e-=+ §bCronic §l§e+=-§r:
  items:
    0:
      id: 276
      damage: 0
      count: 1
      display_name: §l§e-=+ §bCronic §l§e+=-§r
      lore:
      - |2-

        §6Lightning V
      - §9Wither I
      enchants:
        9: 10
        17: 8
        13: 2
        12: 2
        123: 5
        115: 1
    1:
      id: 278
      damage: 0
      count: 1
      display_name: §l§e-=+ §bCronic §l§e+=-§r
      lore:
      - |2-

        §9Haste II
      - §dJackpot V
      enchants:
        15: 10
        17: 7
        16: 1
        207: 2
        212: 5
    2:
      id: 279
      damage: 0
      count: 1
      display_name: §l§e-=+ §bCronic §l§e+=-§r
      lore:
      - ""
      - §6Lumberjack I
      enchants:
        15: 10
        17: 7
        204: 1
    3:
      id: 277
      damage: 0
      count: 1
      display_name: §l§e-=+ §bCronic §l§e+=-§r
      enchants:
        15: 10
        17: 7
    4:
      id: 368
      damage: 0
      count: 16
    5:
      id: 322
      damage: 0
      count: 33
    6:
      id: 466
      damage: 0
      count: 16
    7:
      id: 364
      damage: 0
      count: 32
    27:
      id: 310
      damage: 0
      count: 1
      display_name: §l§e-=+ §bCronic §l§e+=-§r
      lore:
      - |2-

        §eObsidian Shield I
      - §6Implants I
      enchants:
        0: 8
        5: 2
        17: 6
        6: 1
        600: 1
    28:
      id: 311
      damage: 0
      count: 1
      display_name: §l§e-=+ §bCronic §l§e+=-§r
      lore:
      - ""
      - §eObsidian Shield I
      enchants:
        0: 8
        5: 2
        17: 6
    29:
      id: 312
      damage: 0
      count: 1
      display_name: §l§e-=+ §bCronic §l§e+=-§r
      lore:
      - ""
      - §eObsidian Shield I
      enchants:
        0: 8
        5: 2
        17: 6
    30:
      id: 313
      damage: 0
      count: 1
      display_name: §l§e-=+ §bCronic §l§e+=-§r
      lore:
      - |2-

        §eObsidian Shield I
      - §9Gears I
      enchants:
        0: 8
        5: 2
        17: 6
        500: 1
  armor: []
  price: 0.000000
  cooldown: 86400
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§l§e<§c§k:§r§l§e> §cDemeter §l§e<§c§k:§r§l§e>:
  items:
    0:
      id: 310
      damage: 0
      count: 1
      display_name: §l§e<§c§k:§r§l§e> §cDemeter §l§e<§c§k:§r§l§e>
      lore:
      - |2-

        §dAntitoxin I
        §9Focused I
      - §eGlowing I
      enchants:
        0: 12
        17: 7
        604: 1
        603: 1
        601: 1
    1:
      id: 311
      damage: 0
      count: 1
      display_name: §l§e<§c§k:§r§l§e> §cDemeter §l§e<§c§k:§r§l§e>
      lore:
      - |2-

        §6Enraged I
      - §9Tank I
      enchants:
        0: 12
        17: 7
        804: 1
        421: 1
    2:
      id: 312
      damage: 0
      count: 1
      display_name: §l§e<§c§k:§r§l§e> §cDemeter §l§e<§c§k:§r§l§e>
      lore:
      - ""
      - §6Berserker III
      enchants:
        0: 12
        17: 7
        411: 3
    3:
      id: 313
      damage: 0
      count: 1
      display_name: §l§e<§c§k:§r§l§e> §cDemeter §l§e<§c§k:§r§l§e>
      lore:
      - ""
      - §9Gears III
      enchants:
        0: 12
        17: 7
        500: 3
    4:
      id: 276
      damage: 0
      count: 1
      display_name: §l§e<§c§k:§r§l§e> §cDemeter §l§e<§c§k:§r§l§e>
      lore:
      - |2-

        §6Deathbringer V
        §6Lightning V
      - §eBlind I
      enchants:
        9: 8
        17: 10
        13: 1
        12: 4
        102: 5
        123: 5
        101: 1
    5:
      id: 278
      damage: 0
      count: 1
      display_name: §l§e<§c§k:§r§l§e> §cDemeter §l§e<§c§k:§r§l§e>
      lore:
      - |2-

        §9Haste III
        §6Telepathy I
      - §9Autorepair I
      enchants:
        15: 12
        207: 3
        205: 1
        108: 1
        17: 7
    6:
      id: 368
      damage: 0
      count: 16
    7:
      id: 466
      damage: 0
      count: 6
    25:
      id: 438
      damage: 21
      count: 1
    26:
      id: 438
      damage: 21
      count: 1
    34:
      id: 438
      damage: 31
      count: 1
    35:
      id: 438
      damage: 31
      count: 1
  armor: []
  price: 0.000000
  cooldown: 86400
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§l§e<§c§k!!§r§l§e>§aChyros§e<§c§k!!§r§l§e>:
  items:
  - id: 310
    damage: 0
    count: 1
    display_name: §l§e<§c§k!!§r§l§e>§aChyros§e<§c§k!!§r§l§e>§r
    lore:
    - ""
    - §9Meditation I
    enchants:
      0: 7
      17: 3
      602: 1
  - id: 311
    damage: 0
    count: 1
    display_name: §l§e<§c§k!!§r§l§e>§aChyros§e<§c§k!!§r§l§e>§r
    lore:
    - |2-

      §6Endershift III
    - §6Vacuum I
    enchants:
      0: 7
      17: 3
      409: 3
      805: 1
  - id: 312
    damage: 0
    count: 1
    display_name: §l§e<§c§k!!§r§l§e>§aChyros§e<§c§k!!§r§l§e>§r
    lore:
    - ""
    - §6Berserker I
    enchants:
      0: 7
      17: 3
      411: 1
  - id: 313
    damage: 0
    count: 1
    display_name: §l§e<§c§k!!§r§l§e>§aChyros§e<§c§k!!§r§l§e>§r
    lore:
    - ""
    - §9Stomp I
    enchants:
      0: 7
      17: 3
      502: 1
  - id: 276
    damage: 0
    count: 1
    display_name: §l§e<§c§k!!§r§l§e>§aChyros§e<§c§k!!§r§l§e>§r
    lore:
    - |2-

      §eCripple I
      §9Vampire I
    - §eLifesteal III
    enchants:
      9: 6
      13: 1
      12: 1
      109: 1
      111: 1
      100: 3
  - id: 278
    damage: 0
    count: 1
    display_name: §l§e<§c§k!!§r§l§e>§aChyros§e<§c§k!!§r§l§e>§r
    lore:
    - |2-

      §9Energizing I
    - §dJackpot II
    enchants:
      15: 7
      17: 4
      202: 1
      212: 2
  - id: 364
    damage: 0
    count: 25
  - id: 466
    damage: 0
    count: 6
  - id: 368
    damage: 0
    count: 8
  armor: []
  price: 0.000000
  cooldown: 86400
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§l§c=-= §dXypnos §c=-=:
  items:
  - id: 310
    damage: 0
    count: 1
    display_name: §l§c=-= §dXypnos §c=-=
    lore:
    - |2-

      §eGlowing I
    - §6Implants I
    enchants:
      0: 7
      6: 1
      17: 2
      601: 1
      600: 1
  - id: 311
    damage: 0
    count: 1
    display_name: §l§c=-= §dXypnos §c=-=
    lore:
    - |2-

      §9Chicken II
    - §9Parachute I
    enchants:
      0: 7
      17: 2
      801: 2
      800: 1
  - id: 312
    damage: 0
    count: 1
    display_name: §l§c=-= §dXypnos §c=-=
    lore:
    - ""
    - §6Shielded I
    enchants:
      0: 7
      17: 2
      423: 1
  - id: 313
    damage: 0
    count: 1
    display_name: §l§c=-= §dXypnos §c=-=
    lore:
    - ""
    - §9Hardened I
    enchants:
      0: 2
      2: 4
      17: 2
      402: 1
  - id: 276
    damage: 0
    count: 1
    display_name: §l§c=-= §dXypnos §c=-=
    lore:
    - |2-

      §eBlind II
      §9Charge I
    - §9Blessed III
    enchants:
      9: 6
      12: 1
      17: 3
      101: 2
      113: 1
      120: 3
  - id: 278
    damage: 0
    count: 1
    display_name: §l§c=-= §dXypnos §c=-=
    lore:
    - ""
    - §9Quickening II
    enchants:
      15: 6
      17: 3
      203: 2
      16: 1
  - id: 368
    damage: 0
    count: 16
  - id: 262
    damage: 0
    count: 64
  - id: 261
    damage: 0
    count: 1
    display_name: §l§c=-= §dXypnos §c=-=
    lore:
    - |2-

      §9Bounty Hunter II
    - §9Headhunter II
    enchants:
      19: 4
      20: 2
      21: 1
      312: 2
  armor: []
  price: 0.000000
  cooldown: 86400
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
EnchanterKit:
  items:
  - id: 340
    damage: 0
    count: 1
    display_name: §eCommon§r§e Book
    lore:
    - §7Tap ground to get random enchantment
  - id: 340
    damage: 0
    count: 1
    display_name: §9Uncommon§r§e Book
    lore:
    - §7Tap ground to get random enchantment
  - id: 340
    damage: 0
    count: 1
    display_name: §6Rare§r§e Book
    lore:
    - §7Tap ground to get random enchantment
  - id: 340
    damage: 0
    count: 1
    display_name: §dMythic§r§e Book
    lore:
    - §7Tap ground to get random enchantment
  armor: []
  price: 0.000000
  cooldown: 0
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
CommonBook:
  items:
  - id: 340
    damage: 0
    count: 1
    display_name: §eCommon§r§e Book
    lore:
    - §7Tap ground to get random enchantment
  armor: []
  price: 0.000000
  cooldown: 0
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
UncommonBook:
  items:
  - id: 340
    damage: 0
    count: 1
    display_name: §9Uncommon§r§e Book
    lore:
    - §7Tap ground to get random enchantment
  armor: []
  price: 0.000000
  cooldown: 0
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
RareBook:
  items:
  - id: 340
    damage: 0
    count: 1
    display_name: §6Rare§r§e Book
    lore:
    - §7Tap ground to get random enchantment
  armor: []
  price: 0.000000
  cooldown: 60
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
MythicBook:
  items:
  - id: 340
    damage: 0
    count: 1
    display_name: §dMythic§r§e Book
    lore:
    - §7Tap ground to get random enchantment
  armor: []
  price: 0.000000
  cooldown: 0
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§cStarter:
  items:
    0:
      id: 267
      damage: 0
      count: 1
      enchants:
        9: 1
    1:
      id: 257
      damage: 0
      count: 1
      enchants:
        9: 1
    2:
      id: 364
      damage: 0
      count: 26
    27:
      id: 306
      damage: 0
      count: 1
      enchants:
      - 1
    28:
      id: 307
      damage: 0
      count: 1
      enchants:
      - 1
    29:
      id: 308
      damage: 0
      count: 1
      enchants:
      - 1
    30:
      id: 309
      damage: 0
      count: 1
      enchants:
      - 1
  armor: []
  price: 0.000000
  cooldown: 86400
  flags:
    locked: false
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§bPVP:
  items:
    0:
      id: 267
      damage: 0
      count: 1
      enchants:
        9: 2
    1:
      id: 257
      damage: 0
      count: 1
      enchants:
        9: 1
        15: 2
    2:
      id: 364
      damage: 0
      count: 26
    27:
      id: 306
      damage: 0
      count: 1
      enchants:
      - 2
    28:
      id: 307
      damage: 0
      count: 1
      enchants:
      - 2
    29:
      id: 308
      damage: 0
      count: 1
      enchants:
      - 2
    30:
      id: 309
      damage: 0
      count: 1
      enchants:
      - 2
  armor: []
  price: 10000.000000
  cooldown: 84600
  flags:
    locked: false
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§dNeos:
  items:
    0:
      id: 276
      damage: 0
      count: 1
      lore:
      - ""
      - §eAerial I
      enchants:
        9: 4
        12: 1
        17: 4
        114: 1
    1:
      id: 278
      damage: 0
      count: 1
      enchants:
        15: 5
        17: 4
    2:
      id: 368
      damage: 0
      count: 16
    3:
      id: 466
      damage: 0
      count: 64
    4:
      id: 340
      damage: 0
      count: 1
      display_name: §6Rare§r§e Book
      lore:
      - §7Tap ground to get random enchantment
    5:
      id: 340
      damage: 0
      count: 1
      display_name: §9Uncommon§r§e Book
      lore:
      - §7Tap ground to get random enchantment
    27:
      id: 310
      damage: 0
      count: 1
      enchants:
        0: 5
        17: 4
    28:
      id: 311
      damage: 0
      count: 1
      enchants:
        0: 5
        17: 4
    29:
      id: 312
      damage: 0
      count: 1
      enchants:
        0: 5
        17: 4
    30:
      id: 313
      damage: 0
      count: 1
      enchants:
        0: 5
        17: 4
  armor: []
  price: 25000.000000
  cooldown: 604800
  flags:
    locked: false
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§eMiza:
  items:
    0:
      id: 276
      damage: 0
      count: 1
      lore:
      - ""
      - §eAerial I
      enchants:
        9: 6
        12: 3
        17: 4
        114: 1
    1:
      id: 278
      damage: 0
      count: 1
      lore:
      - ""
      - §dJackpot I
      enchants:
        15: 5
        17: 4
        212: 1
    2:
      id: 368
      damage: 0
      count: 16
    3:
      id: 466
      damage: 0
      count: 64
    27:
      id: 310
      damage: 0
      count: 1
      enchants:
        0: 7
        17: 4
    28:
      id: 311
      damage: 0
      count: 1
      enchants:
        0: 7
        17: 4
    29:
      id: 312
      damage: 0
      count: 1
      enchants:
        0: 7
        17: 4
    30:
      id: 313
      damage: 0
      count: 1
      enchants:
        0: 7
        17: 4
    31:
      id: 340
      damage: 0
      count: 1
      display_name: §dMythic§r§e Book
      lore:
      - §7Tap ground to get random enchantment
  armor: []
  price: 50000.000000
  cooldown: 2628002
  flags:
    locked: false
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§cDo§6madia:
  items:
    0:
      id: 267
      damage: 0
      count: 1
      enchants:
        9: 3
        12: 1
        13: 1
    1:
      id: 364
      damage: 0
      count: 26
    27:
      id: 306
      damage: 0
      count: 1
      enchants:
      - 4
    28:
      id: 307
      damage: 0
      count: 1
      enchants:
      - 4
    29:
      id: 308
      damage: 0
      count: 1
      enchants:
      - 4
    30:
      id: 309
      damage: 0
      count: 1
      enchants:
      - 4
  armor: []
  price: 15000.000000
  cooldown: 86400
  flags:
    locked: false
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
§3Vote Package:
  items:
    9:
      id: 310
      damage: 0
      count: 1
      enchants:
      - 3
    10:
      id: 311
      damage: 0
      count: 1
      enchants:
      - 3
    11:
      id: 312
      damage: 0
      count: 1
      enchants:
      - 3
    12:
      id: 313
      damage: 0
      count: 1
      enchants:
      - 3
    18:
      id: 340
      damage: 0
      count: 1
      display_name: §eCommon§r§e Book
      lore:
      - §7Tap ground to get random enchantment
    19:
      id: 339
      damage: 0
      count: 1
      display_name: §r§e$§65000 §enote
      lore:
      - §r§4Right-click §cto deposit this note
      - '§r§cCreated by: §4TetroYT'
    20:
      id: 49
      damage: 0
      count: 32
    27:
      id: 276
      damage: 0
      count: 1
      enchants:
        9: 2
    28:
      id: 278
      damage: 0
      count: 1
      enchants:
        15: 3
  armor: []
  price: 0.000000
  cooldown: 0
  flags:
    locked: true
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true
...

**Comment by AndreasHGK** [comment] 2019-09-26 16:12
I dont see the error yet, I will look into this further. Sorry for the delay.

**Comment by AndreasHGK** [comment] 2019-10-03 14:54
I'm closing this because I don't have enough info to reproduce this.

**Closed by AndreasHGK** 2019-10-03 14:54 UTC

**Comment by AndreasHGK** [comment] 2019-10-04 16:43
I was finally able to reproduce this, and i think i fixed this in the latest dev build. @TetroYT
